name: Release Go Binaries

# IMPORTANT! Is necessary give repository > Settings > Actions > General > `Workflow permissions`: "Read and write permissions"
#    https://github.com/<author>/<repo>/settings/actions#actions_default_workflow_permissions_write

# on:
#   release:
#     types: [created]
#   workflow_dispatch:

on:
  push:
    tags:
      - '*'


env:
  # CMD_PATH: ./cmd/vt2geojson
  CMD_PATH: ./cmd/wol


jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", arm, arm64, amd64]
        exclude:
          # windows/386 and darwin/386 seems useless 
          - goarch: "386"
            goos: windows
          - goarch: arm64
            goos: windows
          - goarch: "386"
            goos: darwin
          - goarch: arm
            goos: darwin
    steps:
      - uses: actions/checkout@v3

      # Create release by tag
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "${{ env.CMD_PATH }}"
          build_flags: -v
          ldflags: -X "main.appVersion=${{ env.APP_VERSION }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}